# Generated by Django 4.2.1 on 2024-03-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('available', models.BooleanField()),
            ],
            options={
                'ordering': ['author'],
            },
        ),
    ]
