# Generated by Django 4.2.1 on 2024-03-23 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='librarybook',
            index_together={('isbn',)},
        ),
    ]
